apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: araneae
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/paloul/araneae.platform
    targetRevision: HEAD
    path: ./turing-pi/distribution
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
