apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: argocd-enable-access
  namespace: argocd
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces: ["istio-system", "argocd"]