apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - secrets/external-dns.yaml
  - manifests/external-dns-v0.14.1.yaml