apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: istio-system # This needs to be same namespace as istio-ingressgateway deployment
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: gateways-cert-issuer
    kind: ClusterIssuer
  dnsNames:
    - argocd.dev.araneae.io
