kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: external-dns
  namespace: kube-system
  creationTimestamp: null
spec:
  template:
    metadata:
      name: external-dns
      namespace: kube-system
      creationTimestamp: null
  encryptedData:
    credentials: AgBBD6iBqR5PijFCprQe8z2CpA5PB34gqswlA/g+221tD4T6FxyVMD8Ack2CPJWsrk+9xtqepiaxM5Tb95gK1JuWT2skHLa30ZY9Kz97PHvMiWdXQDDBpPXR3Y9OdbecJZwlguvMc7IyVlSvxpFvmZ+h4aOPotuheb7s+Vz0CJUuhjB0znHOUJVMfTqufpys0Qh1gG0JA8VBWQG6DC5KUm6jzojSQLnoTgmMkkS7Y9nzNNN7MbmvHxjxWRJtSJFnPfgUqbeVGU+pQ2bj8hnoLfzYM4VnpfHjgkiUCBcyvOaHyxCQBq8ClQ0wDIYqa+HqnmhgndSGYe8E2jMyFqprdtzHwSb9lMzssvZSOKzHED0iEAFpa2CbHdsXiAOrs/VoTMLRE832N/8fAHBnwWoD4+4w8/dokXxmoF61TUTvx6mHDl2kCAJZQcB23CQBDTUHtxecRAwVWyVJpVHWuRTg9sTmC58XRGpeCNpia9hMeJVYAUb4V1beOiR6HUi9Rdsr1uL0v/x51QIldZ1IXx0BQnihw82FDuaZe5KFv/jIh2p1YADS/jhdF+5IL0Zwx/+cO4lGsWzPvxA5v0vnsOu69qPQJ/D+1XPIwLl1nLq09M4vq0yGTSlCNkcYQwpo0meZG3D1dooydm/9Bo/AfZ647Tdl2/q9jpzvrB6PjsxAyKJzE8jtOAmXwqpnZDeymy/Jk83U+wMxcApbp3OWPRHuGeUUgq9j1tj+wUoItaTtOPDCYUKP6O/d1nejD0S8GrcUMWpTlzvGA7zKxWuyukP9rL04+KEOsL3PqqfgMJQ5RJknzcZG8FsRKe9NHY4BodxGoer5U9QS6yumWvRiA5bQsofQeg0EiSI=
