apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress-class.yaml
  - deny-all-authorization-policy.yaml
  - envoy-filter-ingress-gateway-settings.yaml
  - envoy-filter-proxy-protocol.yaml
  - cluster-local-gateway.yaml
  - cluster-local-gateway-authorization-policy.yaml
  - argocd/ingress-gateway.yaml
