apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  # Run server without TLS
  # server.insecure: "false"
  server.insecure: "true"

  # Repo server address. (default "argocd-repo-server:8081")
  repo.server: "argocd-repo-server:8081"
  # Use a plaintext client (non-TLS) to connect to repository server
  server.repo.server.plaintext: "true"

  # Disabling app tls because istio mesh enables mtls via sidecar
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/tls/#disabling-tls-to-argocd-repo-server
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/tls/#disabling-tls-to-argocd-dex-server

  # Dex server address (default "http://argocd-dex-server:5556")
  server.dex.server: "argocd-dex-server:5556"
  # Use a plaintext client (non-TLS) to connect to dex server
  server.dex.server.plaintext: "true"

  # Disable TLS on the gRPC endpoint
  reposerver.disable.tls: "true"
  # Listen on given address for incoming connections (default "0.0.0.0")
  #reposerver.listen.address: "127.0.0.1" # Restrict to localhost since we have istio proxy sidecars

  # Disable TLS on the HTTP endpoint
  dexserver.disable.tls: "true"